[package]
name = "samuel"
version = "0.1.2"
authors = ["Morley, Jonathan <morley.jonathan@gmail.com>"]
edition = "2018"
description = "Rust library for SAML 2.0"
license = "Apache-2.0"

[dependencies]
failure = "0.1"
try_from = "0.3"
roxmltree = "0.4"
